spring:
  application:
    name: flight-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
server:
  port: 8201
  error:
    include-message: always